In [1]:
import pinocchio as pin
import numpy as np
from scipy.spatial.transform import Rotation as R

# Kinematics: configuration 

## Rotation

Consider a physical point $p$ in a 2 dimensional <b>Euclidean space</b> $p \in \varepsilon (2)$. In order to work with numbers, we need to express the physical point $p$ in some <b>coordinate system</b> $\Psi_i$ to get numbers describing $p^i$.   Figure below shows two coordinate systems $\Psi_1$ and $\Psi_2$ rotated with respect to each other of an angle $\theta$, $o=o_1=0_2$ is the <b>origins</b> of the coordinate systems. Let us consider a pure rotation around $o$ in the plane and derive what will be called <b>rotation matrices</b>, which happen to belong to the <b>matrix special orthogonal group</b> $SO(2)$. 

In [25]:
r1 = R.from_euler('zyx', [np.pi, 0, 0], degrees=False)
r1.as_matrix()

array([[-1.0000000e+00, -1.2246468e-16,  0.0000000e+00],
       [ 1.2246468e-16, -1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

In [26]:
r2 = R.from_quat([[1, 1, 0, 0]])
r2.as_matrix()

array([[[ 0.,  1.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  0., -1.]]])

## Homogeneius

In [12]:
M = pin.SE3.Random()
print(M)
print(M.rotation)
print(M.translation)

  R =
 -0.615449   0.639763   0.460354
-0.0555097  -0.617807   0.784368
   0.78622   0.457184   0.415742
  p =  0.898654 0.0519907 -0.827888

[[-0.61544904  0.63976308  0.46035386]
 [-0.0555097  -0.61780713  0.78436792]
 [ 0.78621953  0.45718438  0.41574186]]
[ 0.89865415  0.0519907  -0.8278883 ]


In [ ]:
print(M.inverse())
print(M.action)
print(M.homogeneous)

## Velocities

In [13]:
v = np.array([0,0,0])
w = np.array([0,0,1])
m = pin.Motion(v,w)
m.linear
m.angular

array([0., 0., 1.])